title: Harish's Blog
baseURL: /
params:
  footer:
    content: '&copy; Stackbit-Fresh. All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: images/avatar.png
    tagline: Header Tagline
    title: Harish's Blog
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
